spring:
    data:
        mongodb:
            host: 127.0.0.1
            port: 39998
            database: ESD
            username: iii
            password: dtiisno1!QAZ2wsx

test:
    url: https://lc-esd.iii.com:58001
    companyId: 1
    deviceSeqId: 1
    deviceId: II10ABCDEF0123456789
    priceId:
    fieldId: 1
    roleId:
    policyId: 1
    stationId: 467440

    deviceStatisticsTime: 20191010 00:00:00,20191010 10:00:00
    electricDataTime: 20191001 00:00:00,20191001 10:00:00
