spring:
    data:
        mongodb:
            host: 140.92.24.20
            # host: 140.92.170.57
            port: 39999
            database: ESD_Trial
            username: iii
            password: dtiisno1!

test:
    url: https://lc-esd.iii.com:58001
    companyId: 1
    deviceSeqId: 1
    deviceId: II10ABCDEF0123456789
    priceId:
    fieldId: 1
    roleId:
    policyId: 1
    stationId: 467440

    deviceStatisticsTime: 20191010 00:00:00,20191010 10:00:00
    electricDataTime: 20191001 00:00:00,20191001 10:00:00

mqtt:
    url: tcp://127.0.0.1:1883
    clientId: esd-server-1
    topic: notice
    qos: 2
    timeout: 5000
