spring:
    data:
        mongodb:
            host: 127.0.0.1
            port: 27017
            database: ESD_T_M
            username: iii
            password: dtiisno1!

test:
    email:
    userId:
    companyId: 1
    tradeGroupId: 1
    deviceId:
    priceId:
    fieldId: 1
    roleId:
    policyId: 1
    stationId:
    afcId:
    drId:
    srId:

    deviceStatisticsTime:
    electricDataTime:
    deviceHistoryTime:
    spinReserveDataTime: