server:
  port: 58030
  servlet:
    context-path: /

spring:
  profiles:
    active: default
  freemarker:
    checkTemplateLocation: false

  devtools:
    livereload:
      enabled: false

logging:
  config: classpath:log4j2.yml

monitor:
  email: true
  line: true
  phone: true