spring:
  data:
    mongodb:
      host: ${ESD_MONGO_IP}
      port: ${ESD_MONGO_PORT}
#      database: ESD
      database: ESD-Test
      username: iii
#      password: 1qaz@WSX
      password: dtiisno1!

# silo_mode: dreg
# silo_afcid: 4
# silo_txg: 3
# silo_resid: 1
# silo_afcurl: http://140.92.27.13:8585