server:
  port: 58001
  ssl:
    enabled: false
    key-store: classpath:dtiesd.p12
    key-store-type: PKCS12
    key-password: dtiisno1!
    key-store-password: dtiisno1!
    key-alias: dtiesd
  servlet:
    context-path: /

  undertow:
    accesslog:
      enabled: true
      dir: logs
      pattern: '[%{time,yyyy-MM-dd HH:mm:ss.S z}] %s %m [%h](%b Byte)(%T ms) [%I][%{i,User-Agent}][%{i,Referer}]'

spring:
  profiles:
    active: ${ESD_ENV}
  mvc:
    throw-exception-if-no-handler-found: true
  #    static-path-pattern: /static
  resources:
    add-mappings: false

  devtools:
    livereload:
      port: 58501

logging:
  config: classpath:log4j2.yml

remoteSensing_cron: 10 * * * * ?
checkDisconnect_cron: 15 * * * * ?

spinReserveStatistics_cron: 0 30 1 * * ?
dailyElectricDataReport_cron: 0 30 2 * * ?
actuallyDataCollect_cron: 0 9 * * * ?
forecastDataCollect_cron: 0 0 0/3 * * ?

recalculateAFC_spm_cron: 0 0/15 * * * *
recalculateAFC_aspm_cron: 0 5 1 * * *

remoteSensing: 2 # in minutes, criteria of realtime data check

soda_file: c:/weather

temp_folder: /download

backend_url: http://localhost:58001

permit: /, /asp4/**, /asp3/**, /taipower/**, /thinclient/**, /favicon.ico, /swagger-resources/**, /swagger-ui.html, /v2/api-docs, /webjars/**, /csrf, /resources/**, /debug/**, /qse/**, /meter/**

phoneNotify: false

env:
  prefix: dev

disconnect: 60

afc:
  sbspm:
    A:
      freq: 59.50
      normalPower: 100.00
      highPower: 100.00
      lowPower: 100.00
    B:
      freq: 59.75
      normalPower: 48.00
      highPower: 48.00
      lowPower: 48.00
    C:
      freq: 59.98
      normalPower: 0.00
      highPower: 9.00
      lowPower: -9.00
    D:
      freq: 60.02
      normalPower: 0.00
      highPower: 9.00
      lowPower: -9.00
    E:
      freq: 60.25
      normalPower: -48.00
      highPower: -48.00
      lowPower: -48.00
    F:
      freq: 60.50
      normalPower: -100.00
      highPower: -100.00
      lowPower: -100.00
