server:
  port: 57000
  ssl:
    enabled: false
    key-store: classpath:dtiesd_License
    key-store-password: dtiisno1!
    key-alias: dtiesd
  servlet:
    context-path: /

spring:
  profiles:
    # active: develop
    # active: dti
    active: ${ESD_ENV}

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

  devtools:
    livereload:
      port: 57500

logging:
  config: classpath:log4j2.yml


permit: /, /auth/**, /line/**, /favicon.ico